### ISSUE TITLE
API 21 release

### ISSUE THREAD

**Issue by Bluscream** [dehesselle/dayzsrvip#1]
Can you publish the compiled API 21 dll? I'm hyped to test it ♥

**Comment by dehesselle** [comment]
Thank you for your interest! Luckily for you, the current state is in fact releasable. I still have to update some documentation though, so maybe in half an hour.

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/20863470/6d60cdd8-b9cb-11e6-80d7-72bac1735ace.png)

**Comment by Bluscream** [comment]
https://github.com/dehesselle/dayzsrvip/releases/tag/v0.5

Thank you :)

**Comment by dehesselle** [comment]
It's now released. The first release did not have binaries attached - I know - I have to change my workflow.

**Comment by Bluscream** [comment]
@dehesselle Can you attach a debug version here, please ? :)
