### ISSUE TITLE
Qt gui

### ISSUE THREAD

**Issue by pratik-p** [dehesselle/dayzsrvip#10]
Didn't know where else to ask this, but do you happen to know how I would fix this problem.
I'm trying to make a dialog box with Qt for teamspeak 3. 
https://i.imgur.com/J5gMM8c.png

**Comment by dehesselle** [comment]
I take it this question is unrelated to dayzsrvip and concerns your own project?

Move your project to GitHub (like you did with "Calendar") and work on it publicly. Create an issue there, giving all the details: platform (Windows? Linux? macOS?), what tools you're using (Qt Creator?), how to reproduce it, your previous attempts on resolving this and whatever else you deem important. Come back here with a link to your project/issue.

**Comment by pratik-p** [comment]
Hi, thanks for the reply: https://github.com/pratik-p/Ts3-Poke-Plugin/issues/1

**Comment by dehesselle** [comment]
Cool. I'll close this issue now. Later this day I'll take a look at your project and give you feedback there.
