### ISSUE TITLE
become approved TS3 developer

### ISSUE THREAD

**Issue by dehesselle** [dehesselle/dayzsrvip#2]
My account on mysteamspeak.com is still not activated. Right now I have activation issues but TeamSpeak staff has already responded.

Next step is to check the requirements for releasing the plugin there. From what I've gathered in the forums I need to apply as a developer first.

**Comment by Bluscream** [comment]
You also need to split your package into one for each platform to publish it on myteamspeak.com:
- dayzsrvip_win32.ts3_plugin
- dayzsrvip_win64.ts3_plugin
- dayzsrvip_linux.ts3_plugin
- dayzsrvip_mac.ts3_plugin

I hope you still upload it here :)

P.S. http://forum.teamspeak.com/threads/128024-Developer-Status-Waiting-for-approval

**Comment by dehesselle** [comment]
Don't worry, nothing will change in regards to this repository if the plugin does qualify for a myteamspeak release.

There won't be releases for other platforms though. DayZ is Windows-only, so there's no use for Linux/macOS versions right now. Regardless, I'll check on the naming conventions and will adjust accordingly. But I'll leave that for the next week or so :wink:

**Comment by dehesselle** [comment]
My profile is now under review by the TeamSpeak team. I also checked naming conventions: they don't seem to be very strict about them, but the official plugins include the platform like stated in the post above.

**Comment by dehesselle** [comment]
I've been approved. v0.6 has been submitted, pending review.
Issue stays open until plugin has been approved by TeamSpeak.

**Comment by dehesselle** [comment]
v0.6 is available on myteamspeak.com. 🎉
