### ISSUE TITLE
Use sendPluginCommand as messaging system

### ISSUE THREAD

**Issue by Bluscream** [dehesselle/dayzsrvip#4]
https://github.com/dehesselle/dayzsrvip/blob/master/ts3psdk/include/ts3_functions.h#L254

https://github.com/Bluscream/ts3_sdk_c/blob/master/src/plugin.c#L1025

Please use this instead of channel messages.

**Comment by dehesselle** [comment]
Good point. `sendPluginCommand()` will take over the duty of sending the "control messages" to each other that actually update data. However, due to feedback from testers, "informational messages" to the channel's chat will stay in as optional feature.

**Comment by Bluscream** [comment]
You should keep channel messages enabled but in another way so they don't look messy.

Simple convert the main interface to use pluginMessages like stated in #5 and add a new setting that says "Send Channel messages" which would send a channel message on each change but is nicely formatted.
