### ISSUE TITLE
Change seperator to something not so regular

### ISSUE THREAD

**Issue by Bluscream** [dehesselle/dayzsrvip#6]
https://github.com/dehesselle/dayzsrvip/blob/master/plugin/DayzServerIp.cpp#L31

I think ### is way to easy to be accidently written in a player or server name which would may even be a security risk (Teamspeak can't catch plugin exceptions, so you may created a client crasher right here)

Something like `§$%#` may work better.

**Comment by dehesselle** [comment]
Will this still be an issue when we switch to `sendPluginCommand`? My understanding is that those messages won't be visible.
In general, I don't really care about what separator is used and it can be changed to something else easily. What you're witnessing here is that a lot of stuff is still provisional. :wink:

**Comment by Bluscream** [comment]
> can be changed to something else easily

That would break backwards compatibility completely, so you should find a good one in a early version and don't change it afterwards only if you really need to

**Comment by Bluscream** [comment]
> this messages wont be visible

Thats true but anyone else can send a fake plugin command with broken code to crash other clients if you dont implement proper error handling there

Also think about a server having ### in its name
